apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-redis
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dev-redis
    spec:
      containers:
      - image: redis:5.0.9-alpine
        name: redis
        ports:
        - containerPort: 6379
      serviceAccountName: default
